"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""



def fibs(max_fib_value = None):
    fib1 = 1
    fib2 = 1

    if not max_fib_value:
        max_fib_value = float('inf')

    while fib2 < max_fib_value:
        yield fib2
        fib1, fib2 = fib2, fib1 + fib2


def get_sum_of_even_fibs():
    total = 0
    for fib in fibs(max_fib_value = 4000000):
        if fib % 2 == 0:
            total += fib
    return total

if __name__ == "__main__":
    print(get_sum_of_even_fibs())
